### PR TITLE
PCSA Home Page

### PR DESCRIPTION
**Pull request by calistus**
This is the home page of PCSA project. Buddhi will add more feature and
commit

### CODE REVIEW

**Comment by calistus** [comment]
This is PCSA Home page. Buddhiprabha will add more feature and commit

**Comment by rosariorobinson** [comment]
I guess since you are both working on Android version, do we need an continuous integration on this repo? @sandarumk @shruti-gupta

**Comment by rosariorobinson** [comment]
Also, @sandarumk should review your code. 

@sandarumk once you have reviewed Ilo's code, please comment with +1 merge, then i will merge to develop branch.

**Comment by rosariorobinson** [comment]
@calistus need to make sure that you submit PR again "develop" branch.

**Comment by sandarumk** [comment]
Hi Rose,
I will review the code by the end of today. It's good if we can have
continuous integration. But I think since only two people are committing
the project just making sure that they commiting the code only for
successful builds is enough at this stage.

Dinu

**Pull request merged**
