### PR TITLE
Removed unnecessary activities and removed status bar in Home page.

### PR DESCRIPTION
**Pull request by medhach**

### CODE REVIEW

**Comment by Buddhiprabha** [comment]
The activities you removed are not unnecessary. Also provide a description when sending a PR.

**Comment by medhach** [comment]
I could not find where they are being used.

**Comment by Buddhiprabha** [comment]
@medhach there has been an issue in the last commit and merging. Certain code that needed to be removed has not been removed as a result and some code that needs to be there has been removed. Your PR is correct as it removes the unnecessary code. Re-opening. I will add back the missing code.

**Comment by sandarumk** [comment]
@rosariorobinson  This PR is ready to merge.
@medhach When claiming and issue and making a PR, please mention that in the mailing list before you make the issue, because some other student/contributor can be doing the same thing. As you have seen in the mailing list some other contributor has mentioned the issue and I have asked him/her to continue working on that. So to avoid rework please make sure nobody is working on the issue before you make the changes. Since we do not have a current issue list for this project, you can use the mailing list. So when you hope to do the changes read the mails check the mailing list whether the issue you are going to work is not claimed by another.

**Comment by medhach** [comment]
@Buddhiprabha Thank you :)
@sandarumk Sure, I will submit my proposal for the changes in the mailing list from now.

**Pull request merged**
